name: Deploy todo-app with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ secrets.DO_SSH_PRIVATE_KEY }}

    - name: Verificar claves cargadas (debug opcional)
      run: ssh-add -L

    - name: Deploy on DigitalOcean Droplet
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          set -e
          rm -rf /root/todo-app
          git clone https://github.com/mccabrerac/tareaa.git /root/todo-app
          cd /root/todo-app

          echo "${{ secrets.FIREBASE_ADMIN_KEY }}" > ./backend/todolist-92e56-firebase-adminsdk-fbsvc-e851359006.json

          docker compose down || true
          docker compose up -d --build
        EOF
